#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run lint && npm run test

if [ $2 == "https://github.com/ac-trainees/demostore.git" ]; then
    echo "Are you sure you don't want to push to your fork?"
    exit 1
else
    exit 0
fi
